apiVersion: v1
kind: Service
metadata:
  name: varnish-service      
spec:
  type: ClusterIP              
  selector:
    app: varnish              # Le Service cible les Pods avec le label "app=varnish"
  ports:
    - port: 80                
      targetPort: 80         
