apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: {{ .Values.apache.replicas }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-html
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: apache-html
          configMap:
            name: {{ .Values.apache.configMap.name }}

