apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
data:
  default.vcl: |
    vcl 4.0;

    backend default {
        .host = "apache-service";  
        .port = "80";
    }

    sub vcl_recv {
        return (hash);
    }

